version: '3.3'

services:
  web:
    container_name: runtime_monorepo_web
    ports: 
      - "9000:80"
    build: client/
    depends_on: 
      - server
  server:
    container_name: runtime_monorepo_server
    ports:
      - "4000:4000"
    build: "server/"