version: "3"
services:
  app:
    container_name: runtime_ondemand_bundles_app
    ports:
      - "7000:80"
    build: "shell/"
  bundles-cdn:
    container_name: runtime_ondemand_bundles_cdn
    ports: 
      - "7001:80"
    build: "cdn/"
